#! /usr/bin/env python





from optparse import OptionParser
import sys
import os 
import re

clearedgood = re.compile('^\d+.*(\w)\s+(\w)\s+(\d)+\s+(\d+)')
clearedgood = re.compile('(^\d+)\s+(\w)\s+(\w+)\s+(\w+)\s+(\d*)\s+(\d*)\s+(\w*)')

parser = OptionParser()
parser.usage = "%prog <file> : expand this python configuration"

(options,args) = parser.parse_args()

for a in args:
    print '-',a,'-'*80
    f = open(a,'r')
    for line in f:
        res = clearedgood.match(line)
#         if res:
#             print line,
#             print res.groups()
        if not res: continue
#         print res.groups()
        (id,end,status,action,exitcode,jobexitcode,host)=res.groups()
        if action != 'Cleared':
            print ' '*5,id,end,status,action,exitcode,jobexitcode,host
    f.close()


